fisher60/friendo-bot

bot/cogs/utilities.py
I changed the order of changing the number of reminders a user has and resetting I also included new checks to ensure a reminder was successful before sending the success message. This is to fix the error that setting a reminder with bad args would permanently set reminders to "1," therefore refusing future reminders.
=> Fix (reminders): fix bug on reminder error

bot/__main__.py, bot/cogs/fun.py
Add a function to convert a user's input to alternating case.
=> Feature: alternating case

bot/cogs/fun.py
Added an 8ball command that allows a user to receive answers in an 8ball style
=> feature eight ball

.pre-commit-config.yaml, Pipfile, Pipfile.lock, README.md
Closes #25. This adds a basic `pre-commit` set up that incorporates both `pylint` and `black`.
The first invocation of `pre-commit` generates the following output. I also highly suggest immediate action for this branch in order to propagate its effects to other branches. I'll also add more `pre-commit` hooks and write documentation the development setup.
```bash
$ pipenv run pre-commit install
$ pipenv run pre-commit run --all-files
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook
Fixing README.md
Fixing docker-compose.yml
Fixing bot/cogs/admin.py
Mixed line ending........................................................Passed …
```
=> Feature: `pre-commit` hooks

.pylintrc, bot/meme_api/memegen.py
Added a comment, made the meme update fail print more explicit
=> Fix: update memegen documentation

bot/cogs/fun.py
This is just the .uwu command stolen from Python Discord's seasonalbot, and with slightly less functionality as you can't give it a message ID. It also includes a stolen function from their utils, `replacemany`.
=> added shamelessly stolen .uwu command

bot/cogs/utilities.py, bot/settings.py
added the commit hash to the version. Let me know if its not what you want
=> added git commit hash to version

bot/cogs/fun.py
Closes #73 
also fixed spelling errors in the eightball command
=> Blackjack game

bot/cogs/greetings.py
chooses between random greetings and adjectives, also there is a chance you get a roast one 😛
=> Updated Hello command

bot/__main__.py
Resolved issue #82 
I have removed predefined help command and defined a new Function inside Bot/__main__.py for embed the custom help text.
@fisher60 I ensure there is no merge Conflict
=> Added Custom Help

bot/cogs/fun.py
choose between rock, paper and scissor and play with the  bot
=> Added rock paper scissor command

bot/cogs/fun.py
=> Improved to_sponge command and Created dice roll command

bot/cogs/fun.py
Send `.factorial 10` to get the factorial of 10
#108
=> Implemented factorial command #108

bot/cogs/todo_list.py
Reason for bug was because of the unnecessary `self.add_to_todo_list_tasks` and `self.delete_from_todo_list_tasks`
=> Fixed feature/todo_list

bot/cogs/trivia.py
Fixed some other small bugs that came up in later testing, sorry for making a new PR but wouldn't let me edit the previous one for some reason.
=> Finished Trivia Leaderboard

.gitignore, bot/__init__.py, bot/bot.py, bot/cogs/admin.py, bot/cogs/events.py, bot/cogs/fun.py, bot/cogs/list_of_quotes.py, bot/cogs/todo_list.py, bot/cogs/utilities.py, bot/events_api/__init__.py, bot/meme_api/memegen.py, bot/settings.py
=> Logging setup

bot/__init__.py, bot/settings.py, docker-compose.yml
Second commit, removed files from other branch.
=> Fix: configure docker for logs

bot/__main__.py, bot/bot.py, bot/cogs/wonder_twins.py, bot/resources/wonder_twins.yaml
This adds a command that randomly assembles a phrase based on the classic Wonder Twins cartoon.
closes: #146
=> feature: add wonder twins command

.github/workflows/linting.yml
This is to prevent the lint running twice on a single pull request
=> feature/change lint to only run on PR

Pipfile, Pipfile.lock, bot/__main__.py, bot/cogs/pixelate.py
pixelates a user's pfp, if user not provided then defaults to the author pfp
closes #156
=> Pixelate feature

Pipfile, Pipfile.lock, bot/__main__.py, bot/cogs/user.py, bot/cogs/utilities.py
A utility command which shows basic info on the user in a nice embed
=> Userinfo command

bot/cogs/user.py, bot/resources/user_badges.yaml
Moved `BADGES` dict to a yaml file in resources folder, and removed unnecessary code
=> Code reformat in userinfo command

Pipfile, Pipfile.lock, bot/__init__.py, bot/bot.py, bot/cogs/dogeboard.py, bot/cogs/timezone_tracker.py, bot/graphql.py, docker-compose.yml
This PR will bring a timezone command that users can use to set their timezone and give other users the ability to list their timezones.
Closes #194 
I have also written a GraphQL wrapper for this, and intend to migrate any existing code that uses GraphQL to this wrapper to avoid GraphQL injections.
=> Timezone commands

bot/cogs/timezone_tracker.py
This changes the output of timezone list so that member's times are grouped together in timezones.
This also alters the sort to be based on UTC offset, rather than minutes since midnight.
=> Group tz list output by member's timezones

CONTRIBUTING.md
=> Spelling correction in CONTRIBUTING.md

bot/cogs/http_codes.py
=> Add `http_codes.py`

Dockerfile, bot/__init__.py, bot/__main__.py, bot/bot.py, bot/cogs/admin.py, bot/cogs/advent_of_code.py, bot/cogs/fun.py, bot/cogs/greetings.py, bot/cogs/image_segmentation.py, bot/cogs/pixelate.py, bot/cogs/timezone_tracker.py, bot/cogs/todo_list.py, bot/cogs/user.py, bot/cogs/utilities.py, bot/cogs/wolfram.py, bot/cogs/wonder_twins.py, bot/graphql.py, bot/meme_api/memegen.py, bot/settings.py
Closes #240 Closes #249 
This also changes the GraphQL cog to use the bot's session, makes the bot work on windows hosts, and makes the import order consistent across the bot.
=> Use the same session for the bot and graphql

bot/cogs/advent_of_code.py
This is not fully ready for 2022 AoC, still need to make sure our leaderboard stays up to date
=> WIP: minor tweaks and changes, fixes for 2022

bot/cogs/wonder_twins.py
Text was taken from a previous commit from SaiTama-max, added as Co-author
closes #160
=> Add `brief`, `usage` and `description` to `wonder_twins`

bot/cogs/advent_of_code/_cog.py
This mirrors the ranking on the site
=>  Sort by `local_score` rather than `stars`
